# Site settings
title: Documentação
description: Documentação e-SUS

# Versão atual da documentação
version: 2.0.0

# the subpath of your site, e.g. /blog
baseurl: "/docs"

# Repositório onde está hospedado os fontes deste site
github_repo: https://github.com/sismob/jekyll

exclude: [README.md, Gemfile*, Guardfile]

# Build settings
encoding: utf-8
incremental: true
timezone: America/Sao_Paulo
markdown: redcarpet
redcarpet:
  max_nesting: 4
  extensions:
    - with_toc_data
    - html_toc
    - tables

collections:
  docs:
    output: true
