# Site settings
title: Layout e-SUS AB de Dados e Interface (LEDI AB)
description: Layout e-SUS AB de Dados e Interface (LEDI AB)

# Versão atual da documentação
version: 2.1.0

# the subpath of your site, e.g. /blog
baseurl: "/integracao/v20"

# Repositório onde está hospedado os fontes deste site
github_repo: https://github.com/esusab/integracao-private

# Branch e subdiretório onde estão armazenados os arquivos da documentação,
# relativo ao projeto especificado em `github_repo`
# Deve ter a forma {branch}/{subdiretório}, onde somente a branch é obrigatória
# Exemplo: `2.1/documentacao`, `master`
github_repo_sub: master

exclude: [README.md, Gemfile*, Guardfile]

# Build settings
encoding: utf-8
incremental: true
timezone: America/Sao_Paulo
markdown: redcarpet
redcarpet:
  max_nesting: 4
  extensions:
    - with_toc_data
    - html_toc
    - tables

collections:
  docs:
    output: true
